export { default as Main } from './Main';
export { default as Home } from './Home';
export { default as Portfolio } from './Portfolio';
export { default as About } from './About';
export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as Snake } from './portfolio/snake/Snake';
export { default as NotFound } from './NotFound/NotFound';
export { default as ErrorIcon } from './NotFound/ErrorIcon';
